CC = gcc
TARGET = 32184682_dkuware
OBJS = dkuware.o
CFLAGS = -Wall -g
LDFLAGS = -pthread

all: 32184682_dkuware

32184682_dkuware : dkuware.c
	gcc -o 32184682_dkuware dkuware.c -pthread
clean:
	rm -f 32184682_dkuware
